#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 	 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Google-chrome desktop=1 follow=on
bspc rule -a Code desktop=2 follow=on
bspc rule -a Gnome-terminal desktop=3 follow=on
bspc rule -a Org.gnome.Nautilus desktop=4 follow=on
setxkbmap -option grp:alt_shift_toggle us,mn &
bspc rule -a Screenkey manage=off
xsetroot -cursor_name left_ptr &
# background pic that show ur cpu ram etc (refresh)
$HOME/scripts/treeWallpaper.sh &
# feh --bg-max $HOME/Pictures/helloo.png
picom --experimental-backend --config $HOME/.config/picom/picom.conf &
# $HOME/.config/polybar/nord/launch.sh
# $HOME/polybar-collection/launch.sh
$HOME/.config/polybar/launch.sh --colorblocks
