RELEASE="v9.0.1"
mkdir /tmp/iosevka-font/$RELEASE
cd /tmp/iosevka-font/$RELEASE

wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-aile-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-curly-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-curly-slab-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-etoile-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-curly-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-curly-slab-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-slab-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-ss01-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-ss02-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-ss03-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-ss04-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-ss05-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-ss06-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-ss07-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-ss08-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-ss09-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-ss10-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-ss11-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-ss12-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-ss13-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-ss14-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-ss15-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-ss16-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-ss17-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-fixed-ss18-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-slab-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-ss01-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-ss02-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-ss03-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-ss04-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-ss05-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-ss06-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-ss07-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-ss08-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-ss09-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-ss10-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-ss11-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-ss12-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-ss13-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-ss14-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-ss15-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-ss16-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-ss17-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-ss18-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-curly-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-curly-slab-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-slab-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-ss01-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-ss02-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-ss03-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-ss04-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-ss05-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-ss06-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-ss07-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-ss08-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-ss09-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-ss10-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-ss11-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-ss12-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-ss13-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-ss14-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-ss15-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-ss16-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-ss17-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-iosevka-term-ss18-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-aile-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-curly-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-curly-slab-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-etoile-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-curly-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-curly-slab-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-slab-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-ss01-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-ss02-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-ss03-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-ss04-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-ss05-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-ss06-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-ss07-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-ss08-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-ss09-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-ss10-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-ss11-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-ss12-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-ss13-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-ss14-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-ss15-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-ss16-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-ss17-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-fixed-ss18-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-slab-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-ss01-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-ss02-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-ss03-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-ss04-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-ss05-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-ss06-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-ss07-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-ss08-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-ss09-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-ss10-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-ss11-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-ss12-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-ss13-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-ss14-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-ss15-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-ss16-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-ss17-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-ss18-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-curly-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-curly-slab-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-slab-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-ss01-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-ss02-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-ss03-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-ss04-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-ss05-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-ss06-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-ss07-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-ss08-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-ss09-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-ss10-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-ss11-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-ss12-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-ss13-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-ss14-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-ss15-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-ss16-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-ss17-9.0.1.zip
wget https://github.com/be5invis/Iosevka/releases/download/$RELEASE/ttf-unhinted-iosevka-term-ss18-9.0.1.zip

unzip \*.zip

sudo mkdir /usr/local/share/fonts/iosevka-font
sudo mv *.ttf /usr/local/share/fonts/iosevka-font/.

sudo fc-cache -fv

